#!/usr/bin/env bash
# This script:
#+ Creates the file /var/run/myscript.pid containing its PID
#+ Displays To infinity and beyond indefinitely
#+ Displays I hate the kill command when receiving a SIGTERM signal
#+ Displays Y U no love me?! when receiving a SIGINT signal
#+ Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal
touch /var/run/myscript.pid
trap 'echo I hate the kill command; rm -f /var/run/myscript.pid' 15
trap 'echo Y U no love me?!' 2
trap 'rm -f /var/run/myscript.pid' 3
while
do
	echo "To infinity and beyond"
done
